name: google
favicon: null
layout_spectrum: 0.8066277808975428
typography_spectrum: 0.680003291927278
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.7310774526558816
  lightness: 0.9191958750598133
  saturation: 0.5527125438675284
  rhythmicContrast: 0.8138849071692675
purpose: []
